# Generated by Django 2.2.6 on 2019-10-22 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGInstance',
            fields=[
                ('inst_id', models.UUIDField(default=uuid.uuid4, help_text='ID para esta unidad', primary_key=True, serialize=False)),
                ('inst_on_stock', models.BooleanField(null=True)),
                ('inst_vg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedor.VG')),
            ],
            options={
                'ordering': ['inst_id'],
            },
        ),
    ]
