# Generated by Django 2.2.6 on 2019-10-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_nombre', models.CharField(help_text='Ingrese el nombre de su comuna', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_numtarj', models.CharField(help_text='Ingrese el número de tarjeta', max_length=16, primary_key='True', serialize=False)),
                ('metodo_pago', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default=None, help_text='Seleccione el método de pago', max_length=1)),
                ('pag_numsegur', models.IntegerField(help_text='Ingrese número de seguridad')),
                ('pag_fecvenc', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.CharField(help_text='Ingrese el id de la comuna', max_length=5, primary_key='True', serialize=False)),
                ('reg_nombre', models.CharField(help_text='Ingrese nombre de la región', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_secreta', models.CharField(choices=[('P1', '¿Cuál es el nombre de tu mascota?'), ('P2', '¿Cuál es tu dibujo animado/anime favorito de la infancia?'), ('P3', '¿Cuál es tu color favorito?'), ('P4', '¿Cuál es el significado de la vida?')], default=None, help_text='Elija su pregunta secreta', max_length=2)),
                ('seg_resp', models.TextField(help_text='Ingrese respuesta a la pregunta', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desp_telef', models.CharField(help_text='Ingrese su número de teléfono', max_length=10)),
                ('desp_direccion', models.TextField(help_text='Ingrese su dirección', max_length=100)),
                ('desp_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Comuna')),
                ('desp_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuent_rut', models.CharField(help_text='Ingrese rut Ej: 12345678-9', max_length=9, primary_key='True', serialize=False)),
                ('cuent_email', models.EmailField(help_text='Ingrese email EJ: hola@gmail.com', max_length=30)),
                ('cuent_pass', models.CharField(help_text='Ingrese contraseña', max_length=30)),
                ('cuent_nombre', models.CharField(help_text='Ingrese su nombre', max_length=50)),
                ('cuent_fecnac', models.DateField(default=None)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], default='O', help_text='Ingrese su sexo', max_length=10)),
                ('cuent_desp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Despacho')),
                ('cuent_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Pago')),
                ('cuent_seg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Seguridad')),
            ],
        ),
    ]
