# Generated by Django 2.2.6 on 2019-10-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='cuent_desp',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='cuent_pago',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='cuent_seg',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuent_ape',
            field=models.CharField(default=None, help_text='Ingrese su apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='desp_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Comuna'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='desp_direccion',
            field=models.TextField(default=None, help_text='Ingrese su dirección', max_length=100),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='desp_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Region'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='desp_telef',
            field=models.CharField(default=None, help_text='Ingrese su número de teléfono', max_length=10),
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Seguridad',
        ),
    ]
