# Generated by Django 2.2.6 on 2019-10-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20191026_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='desp_comuna',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='com_nombre',
            field=models.CharField(default=None, help_text='Ingrese el nombre de su comuna', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_id',
            field=models.CharField(help_text='Ingrese el id de la region', max_length=5, primary_key='True', serialize=False),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
